# @package _global_

defaults:
  - _self_
  - data: ljspeech
  - model: matcha
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train"
run_name: "matcha_tts"
tags: ["training"]

train: True
test: True

seed: 1234

trainer:
  max_epochs: 5
  check_val_every_n_epoch: 1
  gradient_clip_val: 1.0

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: /home/victoria/Matcha-TTS/checkpoints
  save_top_k: -1
  monitor: val_loss
  mode: min
  every_n_epochs: 6
  save_last: true
