# @package _global_

defaults:
  - _self_
  - data: ljspeech
  - model: matcha
  - callbacks: default

  - logger: null

  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

logger:
  tensorboard:
    _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    save_dir: ${paths.log_dir}
    name: ${run_name}
  csv:
    _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
    save_dir: ${paths.log_dir}
    name: ${run_name}

task_name: "train"
run_name: "matcha_tts"
tags: ["training"]

train: True
test: True

seed: 1234

trainer:
  max_epochs: 5
  check_val_every_n_epoch: 1
  gradient_clip_val: 1.0

checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: /home/victoria/Matcha-TTS/checkpoints
  save_top_k: 30000
  monitor: val_loss
  mode: min
  every_n_epochs: 50
  save_last: true
